In [255]:
import numpy as np
scores = np.array([
         [20, 40, 56, 80, 0, 5, 25, 27, 74, 1],
         [0, 98, 67, 100, 8, 56, 34, 82, 100, 7],
         [78, 54, 23, 79, 100, 0, 0, 42, 95, 83],
         [51, 50, 47, 23, 100, 94, 25, 48, 38, 77],
         [90, 87, 41, 89, 52, 0, 5, 17, 28, 99],
         [32, 18, 21, 18, 29, 31, 48, 62, 76, 22],
         [6, 0, 65, 78, 43, 22, 38, 88, 94, 100],
         [77, 28, 39, 41, 0, 81, 45, 54, 98, 12],
         [66, 0, 88, 0, 44, 0, 55, 100, 12, 11],
         [17, 70, 86, 96, 56, 23, 32, 49, 70, 80],
         [20, 24, 76, 50, 29, 40, 3, 2, 5, 11],
         [33, 63, 28, 40, 51, 100, 98, 87, 22, 30],
         [16, 54, 78, 12, 25, 35, 10, 19, 67, 0],
         [100, 88, 24, 33, 47, 56, 62, 34, 77, 53],
         [50, 89, 70, 72, 56, 29, 15, 20, 0, 0]])
print(scores)

[[ 20  40  56  80   0   5  25  27  74   1]
 [  0  98  67 100   8  56  34  82 100   7]
 [ 78  54  23  79 100   0   0  42  95  83]
 [ 51  50  47  23 100  94  25  48  38  77]
 [ 90  87  41  89  52   0   5  17  28  99]
 [ 32  18  21  18  29  31  48  62  76  22]
 [  6   0  65  78  43  22  38  88  94 100]
 [ 77  28  39  41   0  81  45  54  98  12]
 [ 66   0  88   0  44   0  55 100  12  11]
 [ 17  70  86  96  56  23  32  49  70  80]
 [ 20  24  76  50  29  40   3   2   5  11]
 [ 33  63  28  40  51 100  98  87  22  30]
 [ 16  54  78  12  25  35  10  19  67   0]
 [100  88  24  33  47  56  62  34  77  53]
 [ 50  89  70  72  56  29  15  20   0   0]]


In [23]:
# Задание 1
# Посчитать, сколько слушателей получили 0 за вступительный экзамен.

count = np.count_nonzero(scores == 0)
print(count)

13


In [156]:
# Задание 2
# Посчитать, сколько слушателей получили балл выше 90.

count = np.count_nonzero(scores > 90)
print(count)

16


In [183]:
# Задание 3
# Посчитать, сколько человек получили балл не ниже 50, но не выше 70.

((scores>= 50) & (scores < 70)).sum()

23

In [184]:
# Задание 4
# Определить, в какой группе средний балл за вступительный экзамен выше.

np.argmax(np.mean(scores, axis = 1))

9

In [225]:
# Задание 5
# Сохранить баллы слушателей выше 0 в массив nonzero.

a = np.array(scores[scores.nonzero()])
print(a)

[ 20  40  56  80   5  25  27  74   1  98  67 100   8  56  34  82 100   7
  78  54  23  79 100  42  95  83  51  50  47  23 100  94  25  48  38  77
  90  87  41  89  52   5  17  28  99  32  18  21  18  29  31  48  62  76
  22   6  65  78  43  22  38  88  94 100  77  28  39  41  81  45  54  98
  12  66  88  44  55 100  12  11  17  70  86  96  56  23  32  49  70  80
  20  24  76  50  29  40   3   2   5  11  33  63  28  40  51 100  98  87
  22  30  16  54  78  12  25  35  10  19  67 100  88  24  33  47  56  62
  34  77  53  50  89  70  72  56  29  15  20]


In [226]:
# Задание 6
# Используя массив nonzero, определить минимальный балл за вступительный балл по всем группам.
# a = sorted(scores[scores.nonzero()])
minV = np.min(scores[scores.nonzero()])
print(minV)

1


In [227]:
# Задание 7
# Выбрать из массива nonzero только те значения, которые соответствуют продвинутому уровню
# знания языка – баллу за экзамен выше 80. Сохранить полученный результат в массив advanced.
advanced = np.array([scores[scores > 80]])
print(advanced)

[[ 98 100  82 100 100  95  83 100  94  90  87  89  99  88  94 100  81  98
   88 100  86  96 100  98  87 100  88  89]]


In [218]:
# Задание 8
# Определить размерность массива advanced.
advanced.dtype


dtype('int32')

In [245]:
# Задание 9
# Определить форму массива advanced.
advanced.shape
advanced.reshape(4,7)

array([[ 98, 100,  82, 100, 100,  95,  83],
       [100,  94,  90,  87,  89,  99,  88],
       [ 94, 100,  81,  98,  88, 100,  86],
       [ 96, 100,  98,  87, 100,  88,  89]])

In [241]:
# Задание 10
# Определить общее число элементов в массиве advanced.
size = advanced.size
print(size)

28


In [256]:
# Задание 11
# На основе исходного массива scores создать булев массив sto,
# где True соответствует баллам за экзамен, равным 100,
# а False – всем остальным баллам.
sto = scores == 100
print(sto)

[[False False False False False False False False False False]
 [False False False  True False False False False  True False]
 [False False False False  True False False False False False]
 [False False False False  True False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False  True]
 [False False False False False False False False False False]
 [False False False False False False False  True False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False  True False False False False]
 [False False False False False False False False False False]
 [ True False False False False False False False False False]
 [False False False False False False False False False False]]


In [177]:
# Задание 12
# На основе исходного массива scores вывести на экран оценки
# слушателей первых семи групп (включительно, должны быть 7 списков оценок).

In [259]:
print(scores[0:7:1])

[[ 20  40  56  80   0   5  25  27  74   1]
 [  0  98  67 100   8  56  34  82 100   7]
 [ 78  54  23  79 100   0   0  42  95  83]
 [ 51  50  47  23 100  94  25  48  38  77]
 [ 90  87  41  89  52   0   5  17  28  99]
 [ 32  18  21  18  29  31  48  62  76  22]
 [  6   0  65  78  43  22  38  88  94 100]]
